optim: adam
init: xavier_uniform
max_epoch: 100
batch_type: folded
batch_size:  160
num_workers: 8
optim_conf:
    lr: 1.0e-03
    eps: 1.0e-08
    weight_decay: 1.0e-7
patience: 10
val_scheduler_criterion:
- valid
- loss
best_model_criterion:
-   - valid
    - si_snr
    - max
-   - valid
    - loss
    - min
keep_nbest_models: 1
scheduler: reducelronplateau
scheduler_conf:
    mode: min
    factor: 0.7
    patience: 1
enh: tf_masking
enh_conf:
    mask_type: PSM
    n_fft: 512
    hop_length: 160
    rnn_type: blstm
    layer: 4
    unit: 1024
    dropout: 0.5
    num_spk: 2
    utt_mvn: True
    nonlinear: relu
    
