optim: adam
init: xavier_uniform
log_interval: 20
max_epoch: 200
batch_type: folded
batch_size: 24
iterator_type: chunk
chunk_length: 16000
num_workers: 4
unused_parameters: true
optim_conf:
    lr: 1.0e-15
    eps: 1.0e-08
    weight_decay: 1.0e-7
patience: 4
val_scheduler_criterion:
- valid
- loss
best_model_criterion:
-   - valid
    - si_snr
    - max
-   - valid
    - loss
    - min
keep_nbest_models: 1
scheduler: reducelronplateau
scheduler_conf:
    mode: min
    factor: 0.9
    patience: 2

enh: asteroid
# Two types of building asteroid
# Second: initialize from the model configuration
enh_conf:
  model_name: ConvTasNet
  n_src : 2
  fs: 8000
  out_chan: None
  n_blocks: 8
  n_repeats: 2
  bn_chan: 128
  hid_chan: 512
  skip_chan: 128
  conv_kernel_size: 3
  norm_type: gLN
  mask_act: sigmoid
  in_chan=: None
  fb_name: free
  kernel_size: 16
  n_filters: 512
  stride: 8
  encoder_activation: None
  sample_rate: 8000

