optim: adam
#init: xavier_uniform
init: none
log_interval: 20
max_epoch: 200
batch_type: folded
batch_size: 24
iterator_type: chunk
chunk_length: 16000
num_workers: 4
unused_parameters: true
optim_conf:
    lr: 1.0e-15
    eps: 1.0e-08
    weight_decay: 1.0e-7
patience: 4
val_scheduler_criterion:
- valid
- loss
best_model_criterion:
-   - valid
    - si_snr
    - max
-   - valid
    - loss
    - min
keep_nbest_models: 1
scheduler: reducelronplateau
scheduler_conf:
    mode: min
    factor: 0.9
    patience: 2

enh: asteroid
# Two types of building asteroid
# First: use the pretrained model
enh_conf:
  n_src : 2
  loss_type: si_snr
  model_name: ConvTasNet
  pretrained_path: mpariente/ConvTasNet_WHAM!_sepclean # choose the pretrained model
