# minibatch related
#batch_type: folded
#batch_size: 8
batch_type: length
batch_bins: 1440000

# optimization related
accum_grad: 3
grad_clip: 5
#max_epoch: 80
max_epoch: 50
patience: none
num_att_plot: 0
unused_parameters: true
# The initialization method for model parameters
init: xavier_uniform
best_model_criterion:
    -   - valid
        - acc
        - max
keep_nbest_models: 10

optim: adam
optim_conf:
    lr: 0.002
scheduler: warmuplr
scheduler_conf:
    warmup_steps: 25000

val_scheduler_criterion:
    - valid
    - loss
#scheduler: reducelronplateau
#scheduler_conf:
#    mode: min
#    factor: 0.5
#    patience: 2
enh: tasnet
enh_conf:
    N: 256
    L: 20
    B: 256
    H: 512
    P: 3
    X: 8
    R: 4
    num_spk: 1
    norm_type: gLN
    causal: False
    mask_nonlinear: relu

# ASR Related
frontend: default
frontend_conf:
    fs: 16000
    n_fft: 512
    win_length: 512
    hop_length: 128
    apply_stft: true

# network architecture
# encoder related
encoder: conformer
encoder_conf:
    output_size: 256
    attention_heads: 4
    linear_units: 2048
    num_blocks: 12
    dropout_rate: 0.1
    positional_dropout_rate: 0.1
    attention_dropout_rate: 0.0
    input_layer: conv2d
    normalize_before: true
    macaron_style: true
    pos_enc_layer_type: rel_pos
    selfattention_layer_type: rel_selfattn
    activation_type: swish
    use_cnn_module: true
    cnn_module_kernel: 31

# decoder related
decoder: transformer
decoder_conf:
    attention_heads: 4
    linear_units: 2048
    num_blocks: 6
    dropout_rate: 0.1
    positional_dropout_rate: 0.1
    self_attention_dropout_rate: 0.0
    src_attention_dropout_rate: 0.0

# hybrid CTC/attention
ctc_conf:
    reduce: true

asr_model_conf:
    ctc_weight: 0.3
    lsm_weight: 0.1
    length_normalized_loss: false

joint_model_conf:
    enh_weight: 0.8
    end2end_train: true
    enh_return_type: waveform # waveform or spectrum or none
    cal_enh_loss: false # whether to calculate enh_loss, need the reduce in ctc_conf
