batch_type: folded
batch_size: 16
# accum_grad: 8
max_epoch: 100
patience: none
# The initialization method for model parameters
init: xavier_uniform
best_model_criterion:
-   - valid
    - acc
    - max
-   - valid
    - loss
    - min
keep_nbest_models: 10

optim: adam
batch_type: folded
num_workers: 2
optim_conf:
    lr: 1.0e-03
    eps: 1.0e-08
    weight_decay: 1.0e-7
val_scheduler_criterion:
    - valid
    - loss_enh
scheduler: reducelronplateau
scheduler_conf:
    mode: min
    factor: 0.9
    patience: 2

# Enhancement Related
enh: wpe_beamformer
enh_conf:
    train_mask_only: False
    mask_type: PSM^2
    loss_type: mask_mse
    n_fft: 512
    win_length: null
    hop_length: 128
    num_spk: 2
    normalize_input: False
    use_wpe: False
    wnet_type: blstmp
    wlayers: 3
    wunits: 300
    wprojs: 320
    wdropout_rate: 0.0
    taps: 5
    delay: 3
    use_dnn_mask_for_wpe: True
    use_beamformer: True
    bnet_type: blstmp
    blayers: 3
    bunits: 512
    bprojs: 512
    badim: 320
    ref_channel: 0
    use_noise_mask: False
    beamformer_type: mvdr_souden
    bdropout_rate: 0.0

# ASR Related
frontend: default
frontend_conf:
    fs: 16000
    n_fft: 512
    win_length: 400
    hop_length: 160
    frontend_conf: null

encoder: transformer
encoder_conf:
    output_size: 256
    attention_heads: 4
    linear_units: 2048
    num_blocks: 12
    dropout_rate: 0.1
    positional_dropout_rate: 0.1
    attention_dropout_rate: 0.0
    input_layer: conv2d
    normalize_before: true

decoder: transformer
decoder_conf:
    attention_heads: 4
    linear_units: 2048
    num_blocks: 6
    dropout_rate: 0.1
    positional_dropout_rate: 0.1
    self_attention_dropout_rate: 0.0
    src_attention_dropout_rate: 0.0

joint_model_conf:
    ctc_weight: 0.3
    lsm_weight: 0.1
    enh_weight: 0.5
    end2end_train: true
    enh_return_type: waveform # waveform or spectrum or none
    cal_enh_loss: true # whether to calculate enh_loss, need the reduce in ctc_conf
    length_normalized_loss: false
