#!/bin/bash
# THIS FILE IS GENERATED BY tools/setup_python.sh
export PYTHONUSERBASE="/search/speech/wangzhichao/espnet/espnet-wzc/tools/python_user_base"
export PATH="/search/speech/wangzhichao/espnet/espnet-wzc/tools/python_user_base/bin":${PATH}
export PATH=/search/speech/wangzhichao/anaconda3/bin:${PATH}
