model-module: espnet.nets.pytorch_backend.e2e_asr_mix:E2E
# minibatch related
batch-size: 2
maxlen-in: 800  # if input length  > maxlen_in, batchsize is automatically reduced
maxlen-out: 150 # if output length > maxlen_out, batchsize is automatically reduced
# optimization related
sortagrad: 0 # Feed samples from shortest to longest ; -1: enabled for all epochs, 0: disabled, other: enabled for 'other' epochs
opt: adadelta
epochs: 3
patience: 2

# scheduled sampling option
sampling-probability: 0.0

# encoder related
etype: vggblstmp     # encoder architecture type
elayers-sd: 1
elayers: 2
eunits: 32
eprojs: 32
subsample: "1_2_2_1_1" # skip every n frame from input to nth layers
# decoder related
dlayers: 1
dunits: 30
# attention related
atype: location
adim: 32
aconv-chans: 4
aconv-filts: 3

# hybrid CTC/attention
mtlalpha: 0.5